apiVersion: v1
kind: Service
metadata:
  name: canvaszero-webapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:381492239882:certificate/3ba190ed-ad5c-4101-83a0-a660ab4ddd1f
  labels:
    app: canvaszero-webapp
spec:
  type: LoadBalancer
  selector:
    app: canvaszero
    name: canvaszero-webapp-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
